"""info -> address in Order model

Revision ID: 2159922612f2
Revises: 84000d4e9108
Create Date: 2025-07-14 15:27:19.270044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2159922612f2'
down_revision: Union[str, None] = '84000d4e9108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('orders', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('info', sa.VARCHAR(), nullable=True))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
